### ISSUE TITLE
Consider dropping use of extra_path in distutils scripts

### ISSUE THREAD

**Issue by jaraco** [ehiggs/pbs-python#1]
In the Python scripts for this project, I find `extra_path = "pbs"`, which according to [Python #27919](http://bugs.python.org/issue27919) is deprecated.

If this feature is something on which you rely heavily, please feel free to post back to the Python ticket explaining your use case and why you think this feature should be retained.

Thanks.

**Comment by ehiggs** [comment]
Hi, in the ticket you said you think this is the parent project. This is actually a fork of [this](https://oss.trac.surfsara.nl/pbs_python) project. I forked it because I think all Python projects should be installable using `python setup.py install` and the original authors disagreed and want to use autotools. Happily they used GPL so I could fork it.

This project will never be migrated to python 3 so I have no issues with removing extra_path. Even if I eat my hat and we do migrate it to python 3, then I'm sure we can fiddle the install to remove any need to use the extra_path setting.

Thanks for reaching out.
